namespace Utilities
{
    public enum AppError
    {
        UNKNOWN,
        OPERATION_FAIL,
        UNAUTHORIZED,
        INVALID_PARAMETERS,
        INVALID_OPERATION,
        PERMISSION_DENIED,
        SYSTEM_BUSY,
        TOO_MANY_REQUESTS,
        RECORD_NOTFOUND,
        TOKEN_INVALID,
        TOKEN_WRONG,
        TOKEN_EXPIRED,
        OTP_INVALID,
        OTP_WRONG,
        OTP_EXPIRED,
        PASSWORD_WRONG,
        GACODE_REQUIRED,
        GACODE_WRONG,
        WRONG_CREDENTIALS,
        USER_INACTIVE,
        USER_BANED,
        INSUFFICIENT_FUNDS,
        EMAIL_EXIST,
        SOLD_OUT,
        OWNER_ERROR,
        GOOGLE_LOGIN_FAIL
    }
}
